[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "superglue_models"
version = "2022.12.21"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
exclude = ["assets"]
